load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2x",
    srcs = glob(["**/*.rs"]),
    crate = "a2x",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2x-derive/0.1.2:a2x_derive",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/env_logger/0.11.11:env_logger",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/miette/7.6.0:miette",
        "//third-party/rust/crates/pest/2.8.8:pest",
        "//third-party/rust/crates/pest_derive/2.8.8:pest_derive",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/unescaper/0.1.10:unescaper",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
        "//third-party/rust/crates/walkdir/2.5.0:walkdir",
        "//third-party/rust/crates/xml/1.4.0:xml",
    ],
)
