load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2c_smcp",
    srcs = glob(["**/*.rs"]),
    crate = "a2c_smcp",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/smcp/0.1.15:smcp",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
