load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_client",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_client",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2a-lf/0.3.0:a2a_lf",
        "//third-party/rust/crates/a2a-pb/0.1.8:a2a_pb",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/auto_impl/1.3.0:auto_impl",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/pin-project-lite/0.2.17:pin_project_lite",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/semver/1.0.28:semver",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
