load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2ui_image",
    srcs = glob(["**/*.rs"]),
    crate = "a2ui_image",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/image/0.25.10:image",
        "//third-party/rust/crates/percent-encoding/2.3.2:percent_encoding",
        "//third-party/rust/crates/ureq/3.4.0:ureq",
    ],
)
