load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_pb",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_pb",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2a-lf/0.3.0:a2a_lf",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/pbjson-types/0.9.0:pbjson_types",
        "//third-party/rust/crates/pbjson/0.9.0:pbjson",
        "//third-party/rust/crates/prost-types/0.14.4:prost_types",
        "//third-party/rust/crates/prost/0.14.4:prost",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tonic-prost/0.14.6:tonic_prost",
        "//third-party/rust/crates/tonic/0.14.6:tonic",
    ],
)
