load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2",
    srcs = glob(["**/*.rs"]),
    crate = "a2",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.20.0:base64",
        "//third-party/rust/crates/erased-serde/0.3.31:erased_serde",
        "//third-party/rust/crates/http/0.2.12:http",
        "//third-party/rust/crates/hyper-alpn/0.4.1:hyper_alpn",
        "//third-party/rust/crates/hyper/0.14.32:hyper",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
