load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_rust",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_rust",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
