load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_protocol_server",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_protocol_server",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2a-protocol-types/0.6.0:a2a_protocol_types",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/http-body-util/0.1.4:http_body_util",
        "//third-party/rust/crates/hyper-util/0.1.20:hyper_util",
        "//third-party/rust/crates/hyper/1.11.0:hyper",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio-util/0.7.19:tokio_util",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
