load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2ui",
    srcs = glob(["**/*.rs"]),
    crate = "a2ui",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/crossterm/0.29.0:crossterm",
        "//third-party/rust/crates/image/0.25.10:image",
        "//third-party/rust/crates/include_dir/0.7.4:include_dir",
        "//third-party/rust/crates/ratatui-image/11.0.6:ratatui_image",
        "//third-party/rust/crates/ratatui/0.30.2:ratatui",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/unicode-width/0.2.2:unicode_width",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
