load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a1",
    srcs = glob(["**/*.rs"]),
    crate = "a1",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/blake3/1.8.6:blake3",
        "//third-party/rust/crates/ed25519-dalek/2.2.0:ed25519_dalek",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/subtle/2.6.1:subtle",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/zeroize/1.9.0:zeroize",
    ],
)
