load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_types",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_types",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/pbjson-types/0.9.0:pbjson_types",
        "//third-party/rust/crates/pbjson/0.9.0:pbjson",
        "//third-party/rust/crates/prost-types/0.14.4:prost_types",
        "//third-party/rust/crates/prost/0.14.4:prost",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
