// With `backend` off the helpers below are unused; `cargo publish` verifies
// with default features (backend off), so silence that rather than cfg-gating
// every item.
#![allow(unused)]

//! Compile the A2UI Slint UI into a Rust module.
//!
//! Slint cannot express recursion (neither recursive structs nor self-
//! referencing components — see slint-ui/slint#4218). A2UI component trees are
//! arbitrarily nested, so we work around this by **unrolling a bounded number
//! of nesting levels**: a chain of components `Node0` (leaf) → `Node1` → … →
//! `Node{MAX_DEPTH}`, where each `NodeK` renders a node and, for its children,
//! instantiates `Node{K-1}`. Because each level references a *different,
//! already-declared* sibling (never itself), Slint resolves it fine. A2UI trees
//! are shallow, so `MAX_DEPTH = 7` covers realistic UIs; deeper subtrees
//! truncate to a `…` marker.
//!
//! To keep the per-kind rendering defined once (not duplicated across levels),
//! `build.rs` generates the whole `.slint` from a single template. Adding a new
//! component kind means editing [`node_body`] below, once.
//!
//! The interactive controls (`TextField`, `Slider`, `CheckBox`, `ChoicePicker`,
//! `Tabs`, `DateTimeInput`) render as **native Slint std-widgets** (`LineEdit`,
//! `Slider`, `CheckBox`, `ComboBox`). Their change callbacks route back through
//! the `Events` global to Rust, which resolves the bound data-model path and
//! writes the new value directly — mirroring the iced/egui backends' direct
//! `DataUpdate` write-back (the shared `core::dispatch_event` only covers
//! key-driven Button/CheckBox/Slider/TextField and is unused for the
//! pointer-driven native widgets here).
//!
//! Only runs under the `backend` feature (slint-build is an optional
//! build-dependency).

use std::path::Path;

/// Maximum renderable nesting depth. `Node0` is the leaf; `Node{MAX_DEPTH}` is
/// what the root `Surface` instantiates. Trees deeper than this truncate.
const MAX_DEPTH: usize = 7;

#[cfg(feature = "backend")]
fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dst = Path::new(&out_dir).join("a2ui_generated.slint");

    let generated = generate();
    std::fs::write(&dst, generated).expect("write generated .slint");

    slint_build::compile(dst.to_str().expect("utf8 path"))
        .expect("Slint UI compilation failed");
}

// Without the `backend` feature, `slint-build` is not a build-dependency, so
// the build script is a no-op. `cargo publish` verifies with default features
// (backend off), so this must compile standalone.
#[cfg(not(feature = "backend"))]
fn main() {}

/// Produce the full `.slint` source: the `LiveNode` struct, the `Events`
/// global (routes UI interactions back to Rust), the `Node0..Node{MAX_DEPTH}`
/// chain, and the root `Surface` window.
fn generate() -> String {
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by crates/slint/build.rs — do not edit.\n");
    out.push_str("// Bounded-depth unrolling of the A2UI component tree (Slint cannot recurse).\n\n");

    // Native interactive widgets from the Slint standard library. (Slint's
    // built-in `Image` element needs no import.)
    out.push_str("import { LineEdit, Slider, CheckBox, ComboBox } from \"std-widgets.slint\";\n\n");

    // One selectable option of a multi-select ChoicePicker.
    out.push_str("struct ChoiceOption {\n    label: string,\n    checked: bool,\n}\n\n");

    // Struct: children are indices into the flat node array (not self-referential).
    out.push_str(
        "struct LiveNode {\n\
         \x20   id: string,\n\
         \x20   kind: string,\n\
         \x20   // Text content / TextField value / CheckBox label / Slider value label.\n\
         \x20   text: string,\n\
         \x20   // Stand-alone label shown above a control (TextField / Slider / ChoicePicker).\n\
         \x20   label: string,\n\
         \x20   variant: string,\n\
         \x20   // CheckBox checked / Modal open.\n\
         \x20   checked: bool,\n\
         \x20   // Slider value / Tabs active index.\n\
         \x20   number: float,\n\
         \x20   // Slider range.\n\
         \x20   min: float,\n\
         \x20   max: float,\n\
         \x20   // ChoicePicker single-select current option index.\n\
         \x20   selected: int,\n\
         \x20   // ChoicePicker multi-select flag.\n\
         \x20   multiple: bool,\n\
         \x20   // TextField / DateTimeInput bound to a writable path.\n\
         \x20   editable: bool,\n\
         \x20   // Image: a decoded raster was supplied.\n\
         \x20   has-image: bool,\n\
         \x20   // Icon emoji / DateTimeInput ISO value / Image url (placeholder).\n\
         \x20   extra: string,\n\
         \x20   // Multi-select ChoicePicker options (label + checked).\n\
         \x20   choices: [ChoiceOption],\n\
         \x20   // Single-select ChoicePicker option labels (ComboBox model).\n\
         \x20   choice-labels: [string],\n\
         \x20   // Tabs header titles.\n\
         \x20   tab-titles: [string],\n\
         \x20   // Decoded image raster for the Image kind (empty otherwise).\n\
         \x20   source: image,\n\
         \x20   focused: bool,\n\
         \x20   children: [int],\n\
         }\n\n",
    );

    // One entry in the gallery's left-hand sample browser. The model position
    // is the sample index used for selection.
    out.push_str(
        "struct SampleEntry {\n\
         \x20   name: string,\n\
         }\n\n",
    );

    // Event bridge global. Each callback carries the node's A2UI id so Rust can
    // resolve the bound data-model path and write the new value back. Rust
    // connects to these via `surface.global::<Events>().on_*`.
    out.push_str(
        "global Events {\n\
         \x20   // Button press (kept for backward compatibility — routes through core dispatch).\n\
         \x20   callback activate(string);\n\
         \x20   // TextField / DateTimeInput text changed: (id, new-text).\n\
         \x20   callback text-edited(string, string);\n\
         \x20   // Slider dragged: (id, new-value).\n\
         \x20   callback slider-changed(string, float);\n\
         \x20   // ChoicePicker single-select pick: (id, selected label).\n\
         \x20   callback choice-selected(string, string);\n\
         \x20   // ChoicePicker multi-select toggle: (id, option-index, now-checked).\n\
         \x20   callback choice-toggled(string, int, bool);\n\
         \x20   // Tabs header click: (id, tab-index).\n\
         \x20   callback tab-selected(string, int);\n\
         \x20   // CheckBox toggled: (id, checked).\n\
         \x20   callback check-toggled(string, bool);\n\
         }\n\n\
         export { Events }\n\n",
    );

    // Node levels: leaf first, then each higher level references the previous.
    for k in 0..=MAX_DEPTH {
        let child = if k == 0 { None } else { Some(format!("Node{}", k - 1)) };
        out.push_str(&node_body(k, child.as_deref()));
        out.push('\n');
    }

    // Root surface: a left-hand sample browser + the rendered A2UI surface.
    out.push_str(&format!(
        "export component Surface inherits Window {{\n\
         \x20   title: \"A2UI Slint Gallery\";\n\
         \x20   preferred-width: 1000px;\n\
         \x20   preferred-height: 700px;\n\
         \x20   in property <[LiveNode]> nodes;\n\
         \x20   in property <[LiveNode]> overlay-nodes;\n\
         \x20   in property <bool> overlay-visible;\n\
         \x20   in property <[SampleEntry]> samples;\n\
         \x20   in property <int> selected-sample;\n\
         \x20   callback select-sample(int);\n\
         \x20   callback close-modal();\n\
         \n\
         \x20   HorizontalLayout {{\n\
         \x20       // Left: sample browser.\n\
         \x20       Rectangle {{\n\
         \x20           width: 220px;\n\
         \x20           background: #f5f5f5;\n\
         \x20           VerticalLayout {{\n\
         \x20               padding: 8px;\n\
         \x20               spacing: 6px;\n\
         \x20               Text {{ text: \"Samples\"; font-weight: 800; }}\n\
         \x20               Flickable {{\n\
         \x20               VerticalLayout {{\n\
         \x20                   for s[i] in root.samples : Rectangle {{\n\
         \x20                       height: 28px;\n\
         \x20                       background: i == root.selected-sample ? #2563eb : transparent;\n\
         \x20                       HorizontalLayout {{\n\
         \x20                           padding-left: 8px;\n\
         \x20                           Text {{\n\
         \x20                               text: s.name;\n\
         \x20                               color: i == root.selected-sample ? #ffffff : #222222;\n\
         \x20                               vertical-alignment: center;\n\
         \x20                           }}\n\
         \x20                       }}\n\
         \x20                       TouchArea {{ clicked => {{ root.select-sample(i); }} }}\n\
         \x20                   }}\n\
         \x20               }}\n\
         \x20               }}\n\
         \x20           }}\n\
         \x20       }}\n\
         \x20       // Divider.\n\
         \x20       Rectangle {{ width: 1px; background: #ddd; }}\n\
         \x20       // Right: the rendered A2UI surface.\n\
         \x20       Node{MAX_DEPTH} {{ all: nodes; idx: 0; }}\n\
         \x20   }}\n\
         \n\
         \x20   // Top-most modal overlay: a dimmed backdrop with a centered dialog\n\
         \x20   // holding the open Modal's content. Declared after the main layout so\n\
         \x20   // it floats above it. Clicking the backdrop closes the modal.\n\
         \x20   if root.overlay-visible : Rectangle {{\n\
         \x20       background: #00000080;\n\
         \x20       TouchArea {{ clicked => {{ root.close-modal(); }} }}\n\
         \x20       HorizontalLayout {{\n\
         \x20           alignment: center;\n\
         \x20           VerticalLayout {{\n\
         \x20               alignment: center;\n\
         \x20               Rectangle {{\n\
         \x20                   background: #fff;\n\
         \x20                   border-radius: 10px;\n\
         \x20                   border-width: 2px; border-color: #c0c0c0;\n\
         \x20                   drop-shadow-blur: 10px; drop-shadow-color: #00000055;\n\
         \x20                   min-width: 300px; min-height: 140px;\n\
         \x20                   VerticalLayout {{\n\
         \x20                       padding: 16px;\n\
         \x20                       Node{MAX_DEPTH} {{ all: root.overlay-nodes; idx: 0; }}\n\
         \x20                   }}\n\
         \x20               }}\n\
         \x20           }}\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n",
    ));

    out
}

/// The body of `Node{k}`. `child_comp` is `Some("Node{k-1}")` for k>0, or `None`
/// for the leaf (k=0), where container children are truncated to a marker.
fn node_body(k: usize, child_comp: Option<&str>) -> String {
    let name = format!("Node{k}");

    // The Slint snippet that renders a container's children. For the leaf level,
    // there is no deeper component to instantiate → emit a truncation marker.
    // (Tabs contributes only its active panel to `me.children` — see
    // live_tree's `build_child_plan` — so this renders just that one panel.)
    //
    // Size-to-content: Slint layouts stretch children to fill the available
    // space by default, so a Column's children would each grow to fill the
    // column's height (and a Row's, its width) instead of taking their natural
    // size — the rendered surface ends up "blown up" rather than packed. We
    // counteract that *per layout direction*: in a vertical container the child
    // keeps filling the width (cross-axis, so wrapping text / full-width
    // controls still work) but takes its natural height (`vertical-stretch: 0`);
    // in a horizontal container it keeps filling the height but takes its natural
    // width (`horizontal-stretch: 0`). Which axis to clamp is a property of the
    // *parent* layout, so we emit two snippets and pick by direction here.
    let render_children_v = match child_comp {
        Some(c) => format!("for c in me.children : {c} {{ all: all; idx: c; vertical-stretch: 0; }}"),
        None => "Text { text: \"…\"; color: #888; }".to_string(),
    };
    let render_children_h = match child_comp {
        Some(c) => format!("for c in me.children : {c} {{ all: all; idx: c; horizontal-stretch: 0; }}"),
        None => "Text { text: \"…\"; color: #888; }".to_string(),
    };

    format!(
        "component {name} inherits Rectangle {{\n\
         \x20   in property <[LiveNode]> all;\n\
         \x20   in property <int> idx;\n\
         \x20   property <LiveNode> me: all[idx];\n\
         \n\
         \x20   // Column — vertical stack.\n\
         \x20   if me.kind == \"Column\" : VerticalLayout {{\n\
         \x20       spacing: 4px;\n\
         \x20       {render_children_v}\n\
         \x20   }}\n\
         \n\
         \x20   // Row — horizontal stack.\n\
         \x20   if me.kind == \"Row\" : HorizontalLayout {{\n\
         \x20       spacing: 4px;\n\
         \x20       {render_children_h}\n\
         \x20   }}\n\
         \n\
         \x20   // Card — bordered panel wrapping one child.\n\
         \x20   if me.kind == \"Card\" : Rectangle {{\n\
         \x20       background: #fff;\n\
         \x20       border-radius: 8px;\n\
         \x20       border-width: 1px;\n\
         \x20       border-color: #d0d0d0;\n\
         \x20       VerticalLayout {{ padding: 10px; {render_children_v} }}\n\
         \x20   }}\n\
         \n\
         \x20   // Text — styled paragraph; variant selects heading/caption styles.\n\
         \x20   if me.kind == \"Text\" : Text {{\n\
         \x20       text: me.text;\n\
         \x20       font-weight: me.variant == \"h1\" || me.variant == \"h2\" || me.variant == \"h3\" ? 800 : 400;\n\
         \x20       color: me.focused ? #1d4ed8 : #111;\n\
         \x20   }}\n\
         \n\
         \x20   // Button — labeled press target; child node is its label.\n\
         \x20   if me.kind == \"Button\" : Rectangle {{\n\
         \x20       background: me.variant == \"primary\" ? #2563eb : #f3f4f6;\n\
         \x20       border-radius: 4px;\n\
         \x20       border-width: me.focused ? 2px : 0px;\n\
         \x20       border-color: #1d4ed8;\n\
         \x20       HorizontalLayout {{ padding: 6px; {render_children_h} }}\n\
         \x20       TouchArea {{ clicked => {{ Events.activate(me.id); }} }}\n\
         \x20   }}\n\
         \n\
         \x20   // TextField — native LineEdit; edits write back via text-edited.\n\
         \x20   if me.kind == \"TextField\" : VerticalLayout {{\n\
         \x20       spacing: 2px;\n\
         \x20       if me.label != \"\" : Text {{ text: me.label; color: #666; font-size: 11px; }}\n\
         \x20       LineEdit {{\n\
         \x20           text: me.text;\n\
         \x20           placeholder-text: me.label;\n\
         \x20           read-only: !me.editable;\n\
         \x20           edited(t) => {{ Events.text-edited(me.id, t); }}\n\
         \x20       }}\n\
         \x20   }}\n\
         \n\
         \x20   // Divider — thin full-width horizontal rule.\n\
         \x20   if me.kind == \"Divider\" : Rectangle {{\n\
         \x20       height: 1px;\n\
         \x20       background: #d0d0d0;\n\
         \x20   }}\n\
         \n\
         \x20   // List — vertical stack of children (same layout as Column).\n\
         \x20   if me.kind == \"List\" : VerticalLayout {{\n\
         \x20       spacing: 2px;\n\
         \x20       {render_children_v}\n\
         \x20   }}\n\
         \n\
         \x20   // CheckBox — native widget; toggled (no-arg) writes back the new state.\n\
         \x20   if me.kind == \"CheckBox\" : CheckBox {{\n\
         \x20       checked: me.checked;\n\
         \x20       text: me.text;\n\
         \x20       toggled => {{ Events.check-toggled(me.id, !me.checked); }}\n\
         \x20   }}\n\
         \n\
         \x20   // Slider — native widget; dragging writes back via slider-changed.\n\
         \x20   if me.kind == \"Slider\" : VerticalLayout {{\n\
         \x20       spacing: 2px;\n\
         \x20       if me.label != \"\" : Text {{ text: me.label; color: #666; font-size: 11px; }}\n\
         \x20       HorizontalLayout {{\n\
         \x20           spacing: 8px;\n\
         \x20           Slider {{\n\
         \x20               value: me.number;\n\
         \x20               minimum: me.min;\n\
         \x20               maximum: me.max;\n\
         \x20               changed(v) => {{ Events.slider-changed(me.id, v); }}\n\
         \x20           }}\n\
         \x20           Text {{ text: me.text; color: #666; vertical-alignment: center; min-width: 36px; }}\n\
         \x20       }}\n\
         \x20   }}\n\
         \n\
         \x20   // Icon — a Unicode glyph (mapped from the name in Rust).\n\
         \x20   if me.kind == \"Icon\" : Text {{\n\
         \x20       text: me.extra;\n\
         \x20       font-size: 20px;\n\
         \x20   }}\n\
         \n\
         \x20   // Tabs — clickable header row + the active child panel only.\n\
         \x20   if me.kind == \"Tabs\" : VerticalLayout {{\n\
         \x20       spacing: 4px;\n\
         \x20       HorizontalLayout {{\n\
         \x20           spacing: 2px;\n\
         \x20           for t[i] in me.tab-titles : Rectangle {{\n\
         \x20               min-width: 64px;\n\
         \x20               height: 26px;\n\
         \x20               background: i == me.number ? #2563eb : #ececec;\n\
         \x20               border-radius: 4px;\n\
         \x20               HorizontalLayout {{\n\
         \x20                   alignment: center;\n\
         \x20                   Text {{ text: t; color: i == me.number ? #ffffff : #333333; vertical-alignment: center; }}\n\
         \x20               }}\n\
         \x20               TouchArea {{ clicked => {{ Events.tab-selected(me.id, i); }} }}\n\
         \x20           }}\n\
         \x20       }}\n\
         \x20       {render_children_v}\n\
         \x20   }}\n\
         \n\
         \x20   // Modal — always renders its trigger child in-place. When open the\n\
         \x20   // content floats as a top-level overlay (see the Surface's overlay-*\n\
         \x20   // properties), so the trigger keeps its place and focus.\n\
         \x20   if me.kind == \"Modal\" : Rectangle {{\n\
         \x20       background: transparent;\n\
         \x20       {render_children_v}\n\
         \x20   }}\n\
         \n\
         \x20   // ChoicePicker (single select) — native ComboBox.\n\
         \x20   if me.kind == \"ChoicePicker\" && !me.multiple : VerticalLayout {{\n\
         \x20       spacing: 4px;\n\
         \x20       if me.label != \"\" : Text {{ text: me.label; color: #666; font-size: 11px; }}\n\
         \x20       ComboBox {{\n\
         \x20           model: me.choice-labels;\n\
         \x20           current-index: me.selected;\n\
         \x20           selected(s) => {{ Events.choice-selected(me.id, s); }}\n\
         \x20       }}\n\
         \x20   }}\n\
         \n\
         \x20   // ChoicePicker (multiple select) — column of native CheckBoxes.\n\
         \x20   if me.kind == \"ChoicePicker\" && me.multiple : VerticalLayout {{\n\
         \x20       spacing: 4px;\n\
         \x20       if me.label != \"\" : Text {{ text: me.label; color: #666; font-size: 11px; }}\n\
         \x20       for o[i] in me.choices : HorizontalLayout {{\n\
         \x20           spacing: 6px;\n\
         \x20           CheckBox {{\n\
         \x20               checked: o.checked;\n\
         \x20               toggled => {{ Events.choice-toggled(me.id, i, !o.checked); }}\n\
         \x20           }}\n\
         \x20           Text {{ text: o.label; vertical-alignment: center; }}\n\
         \x20       }}\n\
         \x20   }}\n\
         \n\
         \x20   // DateTimeInput — editable ISO field (reuses text-edited).\n\
         \x20   if me.kind == \"DateTimeInput\" : VerticalLayout {{\n\
         \x20       spacing: 2px;\n\
         \x20       if me.label != \"\" : Text {{ text: me.label; color: #666; font-size: 11px; }}\n\
         \x20       LineEdit {{\n\
         \x20           text: me.extra;\n\
         \x20           placeholder-text: me.text;\n\
         \x20           read-only: !me.editable;\n\
         \x20           edited(t) => {{ Events.text-edited(me.id, t); }}\n\
         \x20       }}\n\
         \x20   }}\n\
         \n\
         \x20   // Image — a real decoded raster, or a labeled placeholder.\n\
         \x20   if me.kind == \"Image\" && me.has-image : Image {{\n\
         \x20       source: me.source;\n\
         \x20       image-fit: contain;\n\
         \x20   }}\n\
         \x20   if me.kind == \"Image\" && !me.has-image : Rectangle {{\n\
         \x20       background: #f3f4f6; border-width: 1px; border-color: #ddd;\n\
         \x20       HorizontalLayout {{ padding: 6px; Text {{ text: \"[Image: \" + me.extra + \"]\"; color: #666; }} }}\n\
         \x20   }}\n\
         \n\
         \x20   // Video / AudioPlayer — labeled placeholders (no media playback in Slint).\n\
         \x20   if me.kind == \"Video\" : Rectangle {{\n\
         \x20       background: #f3f4f6; border-width: 1px; border-color: #ddd;\n\
         \x20       HorizontalLayout {{ padding: 6px; Text {{ text: \"[Video: \" + me.extra + \"]\"; color: #666; }} }}\n\
         \x20   }}\n\
         \x20   if me.kind == \"AudioPlayer\" : Rectangle {{\n\
         \x20       background: #f3f4f6; border-width: 1px; border-color: #ddd;\n\
         \x20       HorizontalLayout {{ padding: 6px; Text {{ text: \"\u{25b6} [Audio: \" + me.extra + \"]\"; color: #666; }} }}\n\
         \x20   }}\n\
         \n\
         \x20   // Unknown / not-yet-implemented kind — show the kind name so the tree is visible.\n\
         \x20   if me.kind != \"Column\" && me.kind != \"Row\" && me.kind != \"Card\" &&\n\
         \x20      me.kind != \"Text\" && me.kind != \"Button\" && me.kind != \"TextField\" &&\n\
         \x20      me.kind != \"Divider\" && me.kind != \"List\" && me.kind != \"CheckBox\" &&\n\
         \x20      me.kind != \"Slider\" && me.kind != \"Icon\" && me.kind != \"Tabs\" &&\n\
         \x20      me.kind != \"Modal\" && me.kind != \"ChoicePicker\" && me.kind != \"DateTimeInput\" &&\n\
         \x20      me.kind != \"Image\" && me.kind != \"Video\" && me.kind != \"AudioPlayer\" :\n\
         \x20       Rectangle {{\n\
         \x20           background: #fafafa;\n\
         \x20           border-width: 1px; border-color: #ddd;\n\
         \x20           VerticalLayout {{ padding: 6px; Text {{ text: \"[\" + me.kind + \"]\"; color: #888; {render_children_v} }} }}\n\
         \x20       }}\n\
         }}\n",
    )
}
