load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_server",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_server",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2a-lf/0.3.0:a2a_lf",
        "//third-party/rust/crates/a2a-pb/0.1.8:a2a_pb",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/axum/0.8.9:axum",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/hyper/1.11.0:hyper",
        "//third-party/rust/crates/reqwest/0.13.4:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tower-http/0.6.11:tower_http",
        "//third-party/rust/crates/tower/0.5.3:tower",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
