load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_protocol_core",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_protocol_core",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/protocol_transport_core/0.1.1:protocol_transport_core",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
