load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_agents_common",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_agents_common",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2a-agents/0.2.0:a2a_agents",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
