load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a2acli",
    srcs = glob(["**/*.rs"]),
    crate = "a2acli",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2a-rs/0.5.0:a2a_rs",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/clap/4.6.6:clap",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing_subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
