load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_client",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_client",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2a-types/0.1.3:a2a_types",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
