load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2f_utils",
    srcs = glob(["**/*.rs"]),
    crate = "a2f_utils",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/hkdf/0.12.4:hkdf",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/x25519-dalek/2.0.1:x25519_dalek",
    ],
)
