load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a2a_server_rust",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_server_rust",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2a-rs/0.2.0:a2a_rs",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
