// Generated by ggen from A2A ontology
// Do not edit - regenerate with: ggen sync

//! A2A-RS Integration Code
//!
//! This module contains the A2A (Agent-to-Agent) protocol integration code generated
//! from the RDF ontology by ggen. It provides type-safe interfaces for agent communication,
//! task management, and message handling.
//!
//! ## Module Structure
//!
//! - [`adapter`]: Data format adapters (JSON, XML)
//! - [`agent`]: Core agent types and factory
//! - [`converged`]: Unified interfaces combining agent and message types
//! - [`error`]: Unified error handling for all A2A operations
//! - [`handlers`]: Message handlers and routing logic
//! - [`message`]: Message types, priority, and status
//! - [`port`]: Port abstractions for agent I/O
//! - [`task`]: Task execution and management
//!
//! ## Quick Start
//!
//! ```rust,no_run
//! use a2a_generated::prelude::*;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     // Create an agent
//!     let agent = AgentFactory::create_agent("my-type", "agent-1", "My Agent");
//!
//!     // Create a task
//!     let task = Task::new(
//!         "task-1".to_string(),
//!         "Test Task".to_string(),
//!         "test".to_string(),
//!         serde_json::json!({"input": "data"}),
//!     );
//!
//!     // Create a message
//!     let message = Message::new(
//!         "msg-1".to_string(),
//!         MessageType::TaskRequest,
//!         "agent-1".to_string(),
//!         Some("agent-2".to_string()),
//!         serde_json::json!({"task": "data"}),
//!     );
//!
//!     Ok(())
//! }
//! ```

pub mod adapter;
pub mod agent;
pub mod converged;
pub mod error;
pub mod handlers;
pub mod message;
pub mod port;
pub mod task;

// Re-export commonly used types from core modules
pub use adapter::{
    Adapter, AdapterCapabilities, AdapterError, BaseAdapter, JsonAdapter, XmlAdapter,
};
pub use agent::{Agent, AgentBehavior, AgentFactory};
pub use message::{
    Message, MessageError, MessageHandler, MessagePriority, MessageResponse, MessageStatus,
    MessageType,
};
pub use port::{BasicPort, Port, PortData, PortError, PortStats, PortStatus, PortType};
pub use task::{Task, TaskError, TaskExecutor, TaskPriority, TaskResult, TaskStatus};
// NOTE: Two distinct TaskStatus enums exist in this crate:
//   - task::TaskStatus (re-exported above): Pending, InProgress, Completed, Failed, Cancelled
//   - converged::message::TaskStatus: Submitted, Working, InputRequired, Completed, Canceled, Failed, Rejected, AuthRequired, Unknown
// The crate root re-exports only task::TaskStatus to avoid ambiguity. Use the full path
// (e.g., a2a_generated::converged::message::TaskStatus) when the converged variant is needed.

// Re-export unified error types
pub use error::{A2AResult, AgentError as UnifiedAgentError};

// Re-export converged types (includes both agent and message types)
// Note: AgentError from converged is the agent-specific error type
pub use converged::{
    // Agent types
    AgentCapabilities,
    AgentCommunication,
    AgentError,
    AgentExecution,
    AgentHealth,
    AgentIdentity,
    AgentLifecycle,
    AgentMetrics,
    AgentProtocol,
    AgentSecurity,
    AgentState,
    // Security types from agent
    AuditConfig,
    AuditEvent,
    AuthenticationConfig,
    AuthenticationMethod,
    AuthenticationProvider,
    AuthorizationConfig,
    AuthorizationModel,
    AuthorizationRole,
    Capability,
    ComparisonOperator,
    ComplianceConfig,
    ComplianceControl,
    ComplianceFramework,
    ComplianceRequirement,
    ComplianceStandard,
    // Message types
    ConvergedMessage,
    ConvergedMessageType,
    ConvergedPayload,
    DataFormat,
    DestinationType,
    EncryptionAlgorithm,
    EncryptionConfig,
    EncryptionKey,
    EncryptionMode,
    EncryptionRequirements,
    ExecutionMode,
    ExecutionStrategy,
    HandlerAction,
    HandlerPriority,
    HandlerStatus,
    HealthStatus,
    LatencyRequirements,
    MessageEnvelope,
    MessageLifecycle,
    MessageRouter,
    MessageRouting,
    MessageState,
    Permission,
    PermissionScope,
    PermissionType,
    PolicyEffect,
    PolicyPriority,
    PolicyType,
    ProviderType,
    QoSLevel,
    ReliabilityLevel,
    RequirementType,
    ResourceConstraints,
    RetentionPolicy,
    SecurityClassification,
    SecurityPolicies,
    SecurityPolicy,
    SecurityRule,
    ThroughputRequirements,
    UnifiedAgent,
    UnifiedAgentBuilder,
    UnifiedContent,
    ValidationAction,
    ValidationRule,
    ValidationSeverity,
};

// Prelude for easier imports
pub mod prelude {
    pub use super::{
        // Unified error handling
        A2AResult,
        // Core adapter types
        Adapter,
        AdapterCapabilities,
        AdapterError,
        // Core agent types
        Agent,
        AgentBehavior,
        // Converged agent types
        AgentCapabilities,
        AgentCommunication,
        AgentError, // This is the converged::agent::AgentError (agent-specific)
        AgentExecution,
        AgentFactory,
        AgentHealth,
        AgentIdentity,
        AgentLifecycle,
        AgentMetrics,
        AgentProtocol,
        AgentSecurity,
        AgentState,
        // Security types
        AuditConfig,
        AuditEvent,
        AuthenticationConfig,
        AuthenticationMethod,
        AuthenticationProvider,
        AuthorizationConfig,
        AuthorizationModel,
        AuthorizationRole,
        BaseAdapter,
        // Core port types
        BasicPort,
        Capability,
        ComparisonOperator,
        ComplianceConfig,
        ComplianceControl,
        ComplianceFramework,
        ComplianceRequirement,
        ComplianceStandard,
        // Converged message types
        ConvergedMessage,
        ConvergedMessageType,
        ConvergedPayload,
        DataFormat,
        DestinationType,
        EncryptionAlgorithm,
        EncryptionConfig,
        EncryptionKey,
        EncryptionMode,
        EncryptionRequirements,
        ExecutionMode,
        ExecutionStrategy,
        HandlerAction,
        HandlerPriority,
        HandlerStatus,
        HealthStatus,
        JsonAdapter,
        LatencyRequirements,
        // Core message types
        Message,
        MessageEnvelope,
        MessageError,
        MessageHandler,
        MessageLifecycle,
        MessagePriority,
        MessageResponse,
        MessageRouter,
        MessageRouting,
        MessageState,
        MessageStatus,
        MessageType,
        Permission,
        PermissionScope,
        PermissionType,
        PolicyEffect,
        PolicyPriority,
        PolicyType,
        Port,
        PortData,
        PortError,
        PortStats,
        PortStatus,
        PortType,
        ProviderType,
        QoSLevel,
        ReliabilityLevel,
        RequirementType,
        ResourceConstraints,
        RetentionPolicy,
        SecurityClassification,
        SecurityPolicies,
        SecurityPolicy,
        SecurityRule,
        // Core task types
        Task,
        TaskError,
        TaskExecutor,
        TaskPriority,
        TaskResult,
        TaskStatus,
        ThroughputRequirements,
        UnifiedAgent,
        UnifiedAgentBuilder,
        UnifiedAgentError,
        UnifiedContent,
        ValidationAction,
        ValidationRule,
        ValidationSeverity,
        XmlAdapter,
    };
}

// Version information
pub const VERSION: &str = "0.1.0";
pub const ONTOLOGY_VERSION: &str = "1.0.0";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_version() {
        assert!(!VERSION.is_empty());
        assert!(!ONTOLOGY_VERSION.is_empty());
    }

    #[tokio::test]
    async fn test_agent_creation() {
        let agent = AgentFactory::create_agent("test", "123", "Test Agent");
        assert_eq!(agent.id, "123");
        assert_eq!(agent.name, "Test Agent");
        assert_eq!(agent.agent_type, "test");
    }

    #[tokio::test]
    async fn test_task_creation() {
        let task = Task::new(
            "task-123".to_string(),
            "Test Task".to_string(),
            "test".to_string(),
            serde_json::json!({"input": "test"}),
        );
        assert_eq!(task.id, "task-123");
        assert_eq!(task.name, "Test Task");
        assert_eq!(task.task_type, "test");
        assert_eq!(task.priority, TaskPriority::Normal);
        assert_eq!(task.status, TaskStatus::Pending);
    }

    #[tokio::test]
    async fn test_message_creation() {
        let message = Message::new(
            "msg-123".to_string(),
            MessageType::TaskRequest,
            "agent-1".to_string(),
            Some("agent-2".to_string()),
            serde_json::json!({"task": "test"}),
        );
        assert_eq!(message.id, "msg-123");
        assert_eq!(message.source, "agent-1");
        assert_eq!(message.target, Some("agent-2".to_string()));
        assert_eq!(message.message_type, MessageType::TaskRequest);
    }

    #[tokio::test]
    async fn test_port_creation() {
        let port = BasicPort::new(
            "port-123".to_string(),
            "Test Port".to_string(),
            PortType::Output,
        );
        assert_eq!(port.id(), "port-123");
        assert_eq!(port.name(), "Test Port");
        assert_eq!(port.port_type(), PortType::Output);
    }

    #[tokio::test]
    async fn test_adapter_creation() {
        let mut json_adapter = JsonAdapter::new();
        json_adapter
            .initialize(serde_json::json!({}))
            .await
            .unwrap();

        assert_eq!(json_adapter.name(), "json");
        assert_eq!(json_adapter.version(), "1.0.0");

        let test_json = serde_json::json!({"test": "message"});
        let converted = json_adapter.to_a2a(&test_json).await.unwrap();
        assert_eq!(converted, test_json);
    }

    #[test]
    fn test_unified_error_alias() {
        // Verify UnifiedAgentError is an alias for error::AgentError
        let error = UnifiedAgentError::transport("test");
        assert_eq!(error.category(), "transport");
        assert!(error.is_retryable());
    }

    #[test]
    fn test_a2a_result_alias() {
        fn returns_ok() -> A2AResult<String> {
            Ok("success".to_string())
        }

        fn returns_err() -> A2AResult<String> {
            Err(UnifiedAgentError::network("Connection failed"))
        }

        assert!(returns_ok().is_ok());
        assert!(returns_err().is_err());
    }
}

// Benchmark suite
#[cfg(feature = "all-adapters")]
pub mod benchmarks {
    use super::*;
    use criterion::{black_box, criterion_group, criterion_main, Criterion};

    pub fn benchmark_agent_operations(c: &mut Criterion) {
        let mut group = c.benchmark_group("agent_operations");

        group.bench_function("agent_creation", |b| {
            b.iter(|| {
                black_box(AgentFactory::create_agent("test", "123", "Test Agent"));
            })
        });

        group.finish();
    }

    pub fn benchmark_task_operations(c: &mut Criterion) {
        let mut group = c.benchmark_group("task_operations");

        group.bench_function("task_creation", |b| {
            b.iter(|| {
                black_box(Task::new(
                    "task-123".to_string(),
                    "Test Task".to_string(),
                    "test".to_string(),
                    serde_json::json!({"input": "test"}),
                ));
            })
        });

        group.finish();
    }

    pub fn benchmark_message_operations(c: &mut Criterion) {
        let mut group = c.benchmark_group("message_operations");

        group.bench_function("message_creation", |b| {
            b.iter(|| {
                black_box(Message::new(
                    "msg-123".to_string(),
                    MessageType::TaskRequest,
                    "agent-1".to_string(),
                    None,
                    serde_json::json!({"task": "test"}),
                ));
            })
        });

        group.bench_function("message_serialization", |b| {
            let message = Message::new(
                "msg-123".to_string(),
                MessageType::TaskRequest,
                "agent-1".to_string(),
                None,
                serde_json::json!({"task": "test"}),
            );
            b.iter(|| {
                black_box(serde_json::to_string(&message).unwrap());
            })
        });

        group.finish();
    }

    pub fn benchmark_port_operations(c: &mut Criterion) {
        let mut group = c.benchmark_group("port_operations");

        group.bench_function("port_creation", |b| {
            b.iter(|| {
                black_box(BasicPort::new(
                    "port-123".to_string(),
                    "Test Port".to_string(),
                    PortType::Output,
                ));
            })
        });

        group.finish();
    }

    pub fn benchmark_adapter_operations(c: &mut Criterion) {
        let mut group = c.benchmark_group("adapter_operations");

        group.bench_function("json_conversion", |b| {
            let adapter = JsonAdapter::new();
            let test_json = serde_json::json!({"test": "message"});
            b.iter(|| {
                black_box(tokio::task::block_in_place(|| {
                    black_box(adapter.to_a2a(&test_json));
                }));
            })
        });

        group.finish();
    }
}

#[cfg(feature = "all-adapters")]
criterion_group!(
    benches,
    benchmark_agent_operations,
    benchmark_task_operations,
    benchmark_message_operations,
    benchmark_port_operations,
    benchmark_adapter_operations
);
#[cfg(feature = "all-adapters")]
criterion_main!(benches);
