load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_swap_sdk",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_swap_sdk",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/solana-client/2.3.13:solana_client",
        "//third-party/rust/crates/solana-sdk/2.3.1:solana_sdk",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
