load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_rs_server",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_rs_server",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2a-rs-core/1.0.26:a2a_rs_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-stream/0.3.6:async_stream",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/axum/0.7.9:axum",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures/0.3.34:futures",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tower/0.4.13:tower",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
