load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2",
    srcs = glob(["**/*.rs"]),
    crate = "a2",
    crate_root = "src/lib.rs",
    edition = "2021",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.21.7:base64",
        "//third-party/rust/crates/erased-serde/0.3.31:erased_serde",
        "//third-party/rust/crates/http-body-util/0.1.4:http_body_util",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/hyper-rustls/0.26.0:hyper_rustls",
        "//third-party/rust/crates/hyper-util/0.1.20:hyper_util",
        "//third-party/rust/crates/hyper/1.11.0:hyper",
        "//third-party/rust/crates/parking_lot/0.12.5:parking_lot",
        "//third-party/rust/crates/rustls-pemfile/2.2.0:rustls_pemfile",
        "//third-party/rust/crates/rustls/0.22.4:rustls",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
    ],
)
