load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a2ui_egui_gallery",
    srcs = glob(["**/*.rs"]),
    crate = "a2ui_egui_gallery",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2ui-base/0.2.1:a2ui_base",
        "//third-party/rust/crates/a2ui-egui/0.2.1:a2ui_egui",
        "//third-party/rust/crates/a2ui-gallery/0.2.1:a2ui_gallery",
        "//third-party/rust/crates/a2ui-tui/0.2.1:a2ui_tui",
        "//third-party/rust/crates/eframe/0.34.3:eframe",
        "//third-party/rust/crates/egui/0.34.3:egui",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
