load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a_chat",
    srcs = glob(["**/*.rs"]),
    crate = "a_chat",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/async-std/1.13.2:async_std",
        "//third-party/rust/crates/futures/0.3.34:futures",
    ],
)
