load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a",
    srcs = glob(["**/*.rs"]),
    crate = "a2a",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
