load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a0",
    srcs = glob(["**/*.rs"]),
    crate = "a0",
    crate_root = "macro.rs",
    edition = "2021",
    proc_macro = True,

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/proc-macro2/1.0.107:proc_macro2",
        "//third-party/rust/crates/quote/1.0.47:quote",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/syn/2.0.119:syn",
        "//third-party/rust/crates/toml/0.8.23:toml",
    ],
)
