load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2kit",
    srcs = glob(["**/*.rs"]),
    crate = "a2kit",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2kit_macro/0.1.0:a2kit_macro",
        "//third-party/rust/crates/a2kit_macro_derive/0.1.0:a2kit_macro_derive",
        "//third-party/rust/crates/assert_cmd/2.2.2:assert_cmd",
        "//third-party/rust/crates/atty/0.2.14:atty",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/clap/3.2.25:clap",
        "//third-party/rust/crates/colored/2.2.0:colored",
        "//third-party/rust/crates/env_logger/0.9.3:env_logger",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/json/0.12.4:json",
        "//third-party/rust/crates/log/0.4.33:log",
        "//third-party/rust/crates/num-derive/0.3.3:num_derive",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/predicates/2.1.5:predicates",
        "//third-party/rust/crates/regex/1.13.1:regex",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/tree-sitter-applesoft/3.1.1:tree_sitter_applesoft",
        "//third-party/rust/crates/tree-sitter-integerbasic/1.0.3:tree_sitter_integerbasic",
        "//third-party/rust/crates/tree-sitter-merlin6502/1.0.0:tree_sitter_merlin6502",
        "//third-party/rust/crates/tree-sitter/0.20.10:tree_sitter",
    ],
)
