load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2_memory_map",
    srcs = glob(["**/*.rs"]),
    crate = "a2_memory_map",
    crate_root = "bindings/rust/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
