load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_rs",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_rs",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/base64/0.21.7:base64",
        "//third-party/rust/crates/bon/2.3.0:bon",
        "//third-party/rust/crates/buffa-types/0.3.0:buffa_types",
        "//third-party/rust/crates/buffa/0.3.0:buffa",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/connectrpc/0.3.3:connectrpc",
        "//third-party/rust/crates/http-body/1.1.0:http_body",
        "//third-party/rust/crates/http/1.5.0:http",
        "//third-party/rust/crates/prost-types/0.14.4:prost_types",
        "//third-party/rust/crates/prost/0.14.4:prost",
        "//third-party/rust/crates/rustls/0.23.43:rustls",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
        "//third-party/rust/crates/url/2.5.8:url",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
        "//third-party/rust/crates/webpki-roots/0.26.11:webpki_roots",
    ],
)
