load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a2ui_gpui_gallery",
    srcs = glob(["**/*.rs"]),
    crate = "a2ui_gpui_gallery",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2ui-base/0.3.1:a2ui_base",
        "//third-party/rust/crates/a2ui-gallery/0.3.1:a2ui_gallery",
        "//third-party/rust/crates/a2ui-gpui/0.3.1:a2ui_gpui",
        "//third-party/rust/crates/a2ui-tui/0.3.1:a2ui_tui",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/gpui-component-assets/0.5.1:gpui_component_assets",
        "//third-party/rust/crates/gpui-component/0.5.1:gpui_component",
        "//third-party/rust/crates/gpui/0.2.2:gpui",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
