load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a_r_c_h_e_r_y",
    srcs = glob(["**/*.rs"]),
    crate = "a_r_c_h_e_r_y",
    crate_root = "src/lib.rs",
    edition = "2018",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/static_assertions/1.1.0:static_assertions",
    ],
)
