load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_client",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_client",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2a-types/0.2.0:a2a_types",
        "//third-party/rust/crates/bytes/1.12.1:bytes",
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/futures-util/0.3.34:futures_util",
        "//third-party/rust/crates/opentelemetry/0.31.0:opentelemetry",
        "//third-party/rust/crates/pbjson-types/0.9.0:pbjson_types",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
        "//third-party/rust/crates/tracing-opentelemetry/0.32.1:tracing_opentelemetry",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
    ],
)
