load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a",
    srcs = glob(["**/*.rs"]),
    crate = "a",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/chrono/0.4.45:chrono",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
