load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_rs_client",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_rs_client",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2a-rs-core/1.0.26:a2a_rs_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/async-stream/0.3.6:async_stream",
        "//third-party/rust/crates/base64/0.22.1:base64",
        "//third-party/rust/crates/futures-core/0.3.34:futures_core",
        "//third-party/rust/crates/rand/0.8.7:rand",
        "//third-party/rust/crates/reqwest/0.12.28:reqwest",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/tokio-stream/0.1.19:tokio_stream",
        "//third-party/rust/crates/tokio/1.53.1:tokio",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/urlencoding/2.1.3:urlencoding",
        "//third-party/rust/crates/uuid/1.24.0:uuid",
    ],
)
