load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a1_notation",
    srcs = glob(["**/*.rs"]),
    crate = "a1_notation",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/serde/1.0.229:serde",
    ],
)
