load("@buckal//:wrapper.bzl", "rust_binary")

rust_binary(
    name = "a2ui_iced_gallery",
    srcs = glob(["**/*.rs"]),
    crate = "a2ui_iced_gallery",
    crate_root = "src/main.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2ui-base/0.2.1:a2ui_base",
        "//third-party/rust/crates/a2ui-gallery/0.2.1:a2ui_gallery",
        "//third-party/rust/crates/a2ui-iced/0.2.1:a2ui_iced",
        "//third-party/rust/crates/a2ui-tui/0.2.1:a2ui_tui",
        "//third-party/rust/crates/iced/0.14.0:iced",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
    ],
)
