load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2ui_core",
    srcs = glob(["**/*.rs"]),
    crate = "a2ui_core",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2ui-types/0.1.0:a2ui_types",
        "//third-party/rust/crates/a2ui-validation/0.1.0:a2ui_validation",
        "//third-party/rust/crates/async-trait/0.1.92:async_trait",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
