load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2lfile",
    srcs = glob(["**/*.rs"]),
    crate = "a2lfile",
    crate_root = "src/lib.rs",
    edition = "2024",
    features = ["default"],

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2lmacros/3.5.0:a2lmacros",
        "//third-party/rust/crates/fnv/1.0.7:fnv",
        "//third-party/rust/crates/num-traits/0.2.19:num_traits",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
