load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2a_app_ports",
    srcs = glob(["**/*.rs"]),
    crate = "a2a_app_ports",
    crate_root = "src/lib.rs",
    edition = "2024",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/a2a_protocol_core/0.1.1:a2a_protocol_core",
        "//third-party/rust/crates/anyhow/1.0.104:anyhow",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/1.0.69:thiserror",
    ],
)
