load("@buckal//:wrapper.bzl", "rust_library")

rust_library(
    name = "a2ui_validation",
    srcs = glob(["**/*.rs"]),
    crate = "a2ui_validation",
    crate_root = "src/lib.rs",
    edition = "2021",

    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/jsonschema/0.28.3:jsonschema",
        "//third-party/rust/crates/serde/1.0.229:serde",
        "//third-party/rust/crates/serde_json/1.0.151:serde_json",
        "//third-party/rust/crates/thiserror/2.0.20:thiserror",
    ],
)
